# This is a basic workflow to help you get started with Actions

name: Publish Documentation

# Run this workflow on push to main branch or when manually request
# on Github's UI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Generate HTML
        run: |
          cd $GITHUB_WORKSPACE
          docker build -t sphinx_theme .
          docker run -v `pwd`:/docs sphinx_theme sphinx-build -b html . output

      # Install git, configure user details, and set up SSH key
      # Much is borrowed from https://tabris.com/using-deploy-keys-on-github-actions
      - name: Configure git and SSH access
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 0400 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_ed25519
          git config --global user.name "Kernel DocBot"
          git config --global user.email "jhkolb@umn.edu"

      # Clone existing github pages repo, move in new files, and push
      - name: Push New Docs
        run: |
          git clone git@github.com:UMN-Kernel-Object/UMN-Kernel-Object.github.io.git
          rm -rf UMN-Kernel-Object.github.io/docs
          cp -r output UMN-Kernel-Object.github.io/docs
          cd UMN-Kernel-Object.github.io
          rm -rf docs/.buildinfo docs/_sources docs/.doctrees
          git add docs
          git commit --allow-empty -m "Documentation Update `date`"
          git push origin main
